{"uuid": "2698c1cf-8000-471a-bee4-bc2c28731453", "children": ["abe4c432-88b4-453e-800f-10a5491f02fb"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /Users/ivanvoronov/.cache/selenium/chromedriver/mac-arm64/131.0.6778.204/chromedriver unexpectedly exited. Status code was: 1\n\n", "trace": "  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/.venv/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/conftest.py\", line 17, in driver\n    driver = webdriver.Chrome(options=options), webdriver.Firefox(options=options)\n  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/.venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py\", line 62, in __init__\n    self.service.start()\n  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/.venv/lib/python3.10/site-packages/selenium/webdriver/common/service.py\", line 108, in start\n    self.assert_process_still_running()\n  File \"/Users/ivanvoronov/PycharmProjects/pom_uitesting_playground/.venv/lib/python3.10/site-packages/selenium/webdriver/common/service.py\", line 121, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1735398694212, "stop": 1735398696906}], "start": 1735398694212, "stop": 1735398697201}